export const ADD_ITEM_NUMBER_SUCCESS = 'ADD_ITEM_NUMBER_SUCCESS'
export const SUBTRACT_ITEM_NUMBER_SUCCESS = 'SUBTRACT_ITEM_NUMBER_SUCCESS'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_VALIDATETOKEN_SUCCESS = 'AUTH_VALIDATETOKEN_SUCCESS'
